### ISSUE TITLE
Request validation fails if imp.native.request is object

### ISSUE THREAD

**Issue by vipreshjha** [oiime/openrtb-schema-validator#1]
The ORTB Native specs 1.1 allows direct JSON or  JSON-encoded string 
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-Native-Ads-Specification-1-1_2016.pdf

But if I pass native request as JSON object, validation fails.

Request eg. 

`{
  "ext": {},
  "cur": [],
  "allimps": 0,
  "test": 0,
  "regs": {
    "ext": {
      "gdpr": 0
    }
  },
  "source": {},
  "imp": [
    {
      "iframebuster": [],
      "ext": {
        "siteid": null
      },
      "pmp": {
        "ext": {},
        "private_auction": 0,
        "deals": []
      },
      "native": {
        "ext": {},
        "request": {
          "native": {
            "ext": {},
            "plcmtcnt": 1,
            "ver": "1.1",
            "assets": [
              {
                "img": {
                  "h": 627,
                  "hmin": 72,
                  "type": 3,
                  "wmin": 137,
                  "w": 1200
                },
                "required": 1,
                "id": 401
              },
              {
                "data": {
                  "type": 1
                },
                "required": 1,
                "id": 501
              },
              {
                "data": {
                  "type": 11
                },
                "required": 1,
                "id": 502
              },
              {
                "title": {
                  "len": 75
                },
                "required": 1,
                "id": 601
              }
            ],
            "context": 1,
            "plcmttype": 1,
            "contextsubtype": 10
          }
        },
        "battr": [],
        "ver": "1.1",
        "api": []
      },
      "tagid": "",
      "metric ": [],
      "bidfloor": 0,
      "bidfloorcur": "USD",
      "id": "1",
      "secure": 1,
      "instl": 0
    }
  ],
  "bapp": [],
  "site": {
    "id": "dHP",
    "sectioncat": [],
    "ext": {},
    "keywords": "",
    "cat": [],
    "domain": "msn.com",
    "publisher": {
      "ext": {},
      "id": "1111",
      "cat": []
    },
    "page": "https://www.test.com",
    "pagecat": [],
    "content": {
      "ext": {},
      "producer": {
        "ext": {},
        "cat": []
      },
      "data": [],
      "cat": []
    }
  },
  "at": 1,
  "bcat": [
    "IAB25-3",
    "IAB25-2",
    "IAB25-1",
    "IAB26",
    "IAB25-5",
    "IAB25-4"
  ],
  "wlang": [],
  "id": "999999999999999999999",
  "bseat": {},
  "user": {
    "ext": {},
    "geo": {
      "ext": {}
    },
    "id": "9999999999999999",
    "data": []
  },
  "device": {
    "ext": {},
    "geo": {
      "ext": {}
    },
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
    "ip": "1.1.1.1"
  },
  "wseat": [],
  "badv": ["testing.com"]
}`

**Comment by oiime** [comment]
Per OpenRTB specs`native.request` is a string only
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf

However,g if you wish to overwrite it you can do so by cloning and altering the provided schema

```
const schema = schemas.request['2.5'].clone()
schema.root.properties.imp.items.properties.native.properties.request = { type: ['string', 'object'] }
const requestValidator = parser(schema, { removeAdditional: true })
``

**Comment by vipreshjha** [comment]
> Per OpenRTB specs`native.request` is a string only
> https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf
> 
> However,g if you wish to overwrite it you can do so by cloning and altering the provided schema
> 
> ```
> const schema = schemas.request['2.5'].clone()
> schema.root.properties.imp.items.properties.native.properties.request = { type: ['string', 'object'] }
> const requestValidator = parser(schema, { removeAdditional: true })
> ``
> ```

Thanks this works
